theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag

title: Bandit 27-34 solutions
url: https://github.com/int3rsys/Bandit27-34/blob/master/index.md
authro: Ilya Rozentsvaig
description: overthewire.org Bandit level 27-34 solutions
